import type { Metadata } from "next";
import { Figtree, Lexend } from "next/font/google";
import "./globals.css";

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap', // Ensures a better user experience
  variable: '--font-figtree', // Custom CSS variable
});

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${lexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
